language: python
python:
  - "3.5"
env:
- HOME=/home/travis/classam
before_install:
- "sudo mv /home/travis/classam/threepanel /home/travis/classam/vagrant_django"
install:
- "sudo bash /home/travis/classam/vagrant_django/configuration/provision.sh"
- "pip install -r /home/travis/classam/vagrant_django/configuration/requirements.txt"
- "sudo python /home/travis/classam/vagrant_django/configuration/install.py"
script:
- "pushd /home/travis/classam/vagrant_django/threepanel; invoke test; popd;"
