language: python
python:
  - "3.5"
before_install:
- sudo apt-get -qq update
- sudo apt-get install -y build-essential gcc
- sudo apt-get -qq install libfreetype6-dev liblcms2-dev python-qt4 ghostscript libffi-dev libjpeg-turbo-progs cmake imagemagick
- sudo apt-get install -y libxml2-dev
- sudo apt-get install -y optipng
install:
- pwd
- sudo mv /home/travis/build/classam/threepanel /home/travis/build/classam/vagrant_django
- export HOME=/home/travis/build/classam
- export VIRTUALENV=/home/travis/virtualenv
- pip install -r /home/travis/build/classam/vagrant_django/configuration/requirements.txt
- sudo python /home/travis/build/classam/vagrant_django/configuration/install.py
script:
- pushd /home/travis/build/classam/vagrant_django/threepanel; invoke test; popd;
