language: python
python:
  - "3.5"
install:
- "pwd"
- "sudo mv /home/travis/build/classam/threepanel /home/travis/build/classam/vagrant_django"
- "export HOME=/home/travis/build/classam"
- "sudo bash /home/travis/build/classam/vagrant_django/configuration/provision.sh"
- "pip install -r /home/travis/build/classam/vagrant_django/configuration/requirements.txt"
- "sudo python /home/travis/build/classam/vagrant_django/configuration/install.py"
script:
- "pushd /home/travis/build/classam/vagrant_django/threepanel; invoke test; popd;"
