language: python
python:
  - "3.5"
#install:
#- "sudo bash ./config/provision.sh"
#- "pip install -r configuration/requirements.txt"
#- "sudo python configuration/install.py"
script:
- "echo $HOME"
- "ls $HOME"
#- "pushd threepanel; invoke test; popd threepanel;"
